[build]
  publish = "."
  command = "echo 'No build process required for static site'"

[build.environment]
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; img-src 'self' https: data:; font-src 'self' https: data:;"

# Redirect rules for better SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Form submission handling
[forms]
  [forms.settings]
    honeypot = "bot-field"
